QuestRoom/Models/CategoryRoomsModel.cs
using QuestRoom.Data.Entity;
using System.Collections.Generic;

namespace QuestRoom.Models
{
    public class CategoryRoomsModel
    {
        public IEnumerable<Room> Rooms { get; set; }
        public IEnumerable<Picture> Pictures { get; set; }
    }
}

QuestRoom/Models/RedactorRoomModel.cs
using QuestRoom.Data.Entity;
using System.Web.Mvc;

namespace QuestRoom.Models
{
    public class RedactorRoomModel
    {
        public Room Room { get; set; }
        public SelectList TypeRoomList { get; set; }
        public SelectList LevelComplexityList { get; set; }
    }
}

QuestRoom/Models/RoomModel.cs
using QuestRoom.Data.Entity;

namespace QuestRoom.Models
{
    public class RoomModel
    {
        public Room Room { get; set; }
        public TypeRoom TypeRoom {get;set;}
        public LevelComplexity LevelComplexity { get; set; }
        public RoomModel(Room room, TypeRoom typeRoom, LevelComplexity levelComplexity)
        {
            Room = room;
            TypeRoom = typeRoom;
            LevelComplexity = levelComplexity;
        }
    }
}

QuestRoom/Models/RoomsAndPictureModel.cs
using QuestRoom.Service.Absractions;

namespace QuestRoom.Models
{
    public class RoomsAndPictureModel
    {
        public IRoomService RoomService { get; set; }
        public IPictureService PictureService { get; set; }
        public ILevelComplexityService LevelComplexityService { get; set; }
        public ITypeRoomService TypeRoomService { get; set; }

        public RoomsAndPictureModel(IRoomService roomService, IPictureService pictureService,
            ILevelComplexityService levelComplexityService, ITypeRoomService typeRoomService)
        {
            RoomService = roomService;
            PictureService = pictureService;
            TypeRoomService = typeRoomService;
            LevelComplexityService = levelComplexityService;
        }
    }
}

QuestRoom/Controllers/HomeController.cs
using System.Web.Mvc;

using QuestRoom.Models;
using QuestRoom.Service.Absractions;

namespace QuestRoom.Controllers
{
    public class HomeController : Controller
    {
        private RoomsAndPictureModel _model;

        public HomeController(IRoomService roomService, IPictureService pictureService,
            ITypeRoomService typeRoomService, ILevelComplexityService levelComplexityService)
        {
            _model = new RoomsAndPictureModel(roomService, pictureService, levelComplexityService, typeRoomService);
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(_model);
        }
    }
}

QuestRoom/Controllers/RedactorController.cs
using QuestRoom.Models;
using QuestRoom.Service.Absractions;
using System.Web.Mvc;

namespace QuestRoom.Controllers
{
    public class RedactorController : Controller
    {

        private RoomsAndPictureModel _roomsAndPictureModel;
        private RedactorRoomModel _redactorRoomModel;

        public RedactorController(IRoomService roomService, IPictureService pictureService,
            ITypeRoomService typeRoomService, ILevelComplexityService levelComplexityService)
        {
            _roomsAndPictureModel = new RoomsAndPictureModel(roomService, pictureService, levelComplexityService, typeRoomService);
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(_roomsAndPictureModel);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var removeRoom = _roomsAndPictureModel.RoomService.GetRoomById(id.Value);
            _roomsAndPictureModel.RoomService.RemoveRoom(removeRoom);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Update(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var updateRoom = _roomsAndPictureModel.RoomService.GetRoomById(id.Value);
            _redactorRoomModel = new RedactorRoomModel()
            {
                Room = updateRoom,
                TypeRoomList = new SelectList(_roomsAndPictureModel.TypeRoomService.GetTypeRoom(), "Id", "Name"),
                LevelComplexityList = new SelectList(_roomsAndPictureModel.LevelComplexityService.GetLevelComplexity(), "Id", "Name")
            };
            return View(_redactorRoomModel);
        }

        [HttpPost]
        public ActionResult Update(RedactorRoomModel model)
        {
            _roomsAndPictureModel.RoomService.UpdateRoom(model.Room);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Create()
        {
            _redactorRoomModel = new RedactorRoomModel()
            {
                Room = null,
                TypeRoomList = new SelectList(_roomsAndPictureModel.TypeRoomService.GetTypeRoom(), "Id", "Name"),
                LevelComplexityList = new SelectList(_roomsAndPictureModel.LevelComplexityService.GetLevelComplexity(), "Id", "Name")
            };
            return View(_redactorRoomModel);
        }

        [HttpPost]
        public ActionResult Create(RedactorRoomModel model)
        {
            _roomsAndPictureModel.RoomService.AddRoom(model.Room);
            return RedirectToAction("Index");
        }
    }
}

QuestRoom/Controllers/RoomController.cs
using System.Linq;
using System.Web.Mvc;

using QuestRoom.Models;
using QuestRoom.Service.Absractions;

namespace QuestRoom.Controllers
{
    public class RoomController : Controller
    {
        private IRoomService _roomService;
        private IPictureService _pictureService;
        private ITypeRoomService _typeRoomService;
        private ILevelComplexityService _levelComplexityService;
        public RoomController(IRoomService roomService, IPictureService pictureService,
            ITypeRoomService typeRoomService, ILevelComplexityService levelComplexityService)
        {
            this._roomService = roomService;
            this._pictureService = pictureService;
            _typeRoomService = typeRoomService;
            _levelComplexityService = levelComplexityService;
        }

        [HttpGet]
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var room = _roomService.GetRoomById(id.Value);
            var typeRoom = _typeRoomService.GetTypeRoomById(room.TypeRoomId);
            var levelComplexity = _levelComplexityService.GetLevelComplexityById(room.LevelComplexityId);
            RoomModel model = new RoomModel(room, typeRoom, levelComplexity);
            model.Room.Pictures = _pictureService.GetPictures().ToList().FindAll(x => x.RoomId == id);
            return View(model);
        }

        [HttpGet]
        public ActionResult TypeRoom(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var model = new CategoryRoomsModel();
            model.Rooms = _roomService.GetRooms().ToList().FindAll(x => x.TypeRoomId == id);
            return View(model);
        }

        [HttpGet]
        public ActionResult LevelComplexity(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var model = new CategoryRoomsModel();
            model.Rooms = _roomService.GetRooms().ToList().FindAll(x => x.LevelComplexityId == id);
            return View(model);
        }
    }
}

QuestRoom/Views/Home/Index.cshtml
@using QuestRoom.Models

@model RoomsAndPictureModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@HomeHelper.HtmlList(Model)
<div>
    <p>Вы так же можете выбрать комнату по следующим типам:</p>
    <p>По жанру квест-комнаты:</p>
    @TypeRoomHelper.HtmlList(Model)
    <p>По уровню сложности квеста:</p>
    @LevelComplexityHelper.HtmlList(Model)
</div>

QuestRoom/Views/Redactor/Create.cshtml
@using QuestRoom.Models;

@model RedactorRoomModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <h2>Новая Квест-комната</h2>
    @using (Html.BeginForm())
    {
        @Html.LabelFor(m => m.Room.Name, "Название комнаты")
        <br />
        @Html.EditorFor(model => model.Room.Name)
        <br /><br />
        @Html.LabelFor(m => m.Room.Description, "Описание")
        <br />
        @Html.EditorFor(m => m.Room.Description)
        <br /><br />
        @Html.LabelFor(m => m.Room.Duration, "Время прохождения")
        <br />
        @Html.EditorFor(m => m.Room.Duration)
        <br /><br />
        @Html.LabelFor(m => m.Room.GroupSize, "Количество игроков")
        <br />
        @Html.EditorFor(m => m.Room.GroupSize)
        <br /><br />
        @Html.LabelFor(m => m.Room.MinimumAge, "Ограничение по возрасту")
        <br />
        @Html.EditorFor(m => m.Room.MinimumAge)
        <br /><br />
        @Html.LabelFor(m => m.Room.Rating, "Рейтинг")
        <br />
        @Html.EditorFor(m => m.Room.Rating)
        <br /><br />
        @Html.LabelFor(m => m.Room.LevelComplexityId, "Урoвень сложности")
        <br />
        @Html.DropDownListFor(m => m.Room.LevelComplexityId, Model.LevelComplexityList as SelectList)
        <br /><br />
        @Html.LabelFor(m => m.Room.TypeRoomId, "Тип комнаты")
        <br />
        @Html.DropDownListFor(m => m.Room.TypeRoomId, Model.TypeRoomList as SelectList)
        <br /><br />
        @Html.LabelFor(m => m.Room.Address, "Адрес")
        <br />
        @Html.EditorFor(m => m.Room.Address)
        <br /><br />
        @Html.LabelFor(m => m.Room.PhoneNumbers, "Телефон")
        <br />
        @Html.EditorFor(m => m.Room.PhoneNumbers)
        <br /><br />
        @Html.LabelFor(m => m.Room.Email, "Емейл")
        <br />
        @Html.EditorFor(m => m.Room.Email)
        <br /><br />
        @Html.LabelFor(m => m.Room.Company, "Компания")
        <br />
        @Html.EditorFor(m => m.Room.Company)
        <br /><br />
        <input type="submit" value="Добавить" />
    }
</body>
</html>

QuestRoom/Views/Redactor/Index.cshtml
@using QuestRoom.Models

@model RoomsAndPictureModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RedactorIndexHelper.HtmlList(Model)
    <p><a href="Redactor/Create" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Добавить квест</a></p>
</body>
</html>

QuestRoom/Views/Redactor/Update.cshtml
@using QuestRoom.Models;

@model RedactorRoomModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        <h3>Форма изменения комнаты</h3>
        @using (Html.BeginForm("Update", "Redactor", FormMethod.Post))
        {
    <fieldset>
        <p>
            @Html.HiddenFor(m => m.Room.Id)
        </p>
        <p>
            @Html.LabelFor(m => m.Room.Name, "Название квеста")
            <br />
            @Html.EditorFor(m => m.Room.Name)
        </p>
        <p>
            @Html.LabelFor(m => m.Room.MinimumAge, "Ограничение по возрасту")
            <br />
            @Html.EditorFor(m => m.Room.MinimumAge)

        </p>
        <p>
            @Html.LabelFor(m => m.Room.Description, "Описание")
            <br />
            @Html.EditorFor(m => m.Room.Description)

        </p>
        <p>
            @Html.LabelFor(m => m.Room.Duration, "Время прохождения")
            <br />
            @Html.EditorFor(m => m.Room.Duration)

        </p>
        <p>
            @Html.LabelFor(m => m.Room.GroupSize, "Количество игроков")
            <br />
            @Html.EditorFor(m => m.Room.GroupSize)

        </p>
        <p>
            @Html.LabelFor(m => m.Room.TypeRoomId, "Тип комнаты")
            <br />
            @Html.DropDownListFor(m => m.Room.TypeRoomId, Model.TypeRoomList as SelectList)
        </p>
        <p>
            @Html.LabelFor(m => m.Room.TypeRoomId, "Уровень сложности")
            <br />
            @Html.DropDownListFor(m => m.Room.LevelComplexityId, Model.LevelComplexityList as SelectList)
        </p>
        <p>
            @Html.LabelFor(m => m.Room.Rating, "Рейтинг")
            <br />
            @Html.EditorFor(m => m.Room.Rating)

        </p>
        <p>
            @Html.LabelFor(m => m.Room.PhoneNumbers, "Номер телефона")
            <br />
            @Html.EditorFor(m => m.Room.PhoneNumbers)

        </p>
        <p>
            @Html.LabelFor(m => m.Room.Company, "Компания")
            <br />
            @Html.EditorFor(m => m.Room.Company)

        </p>
        <p>
            @Html.LabelFor(m => m.Room.Address, "Адрес")
            <br />
            @Html.EditorFor(m => m.Room.Address)
        </p>
        <p>
            @Html.LabelFor(m => m.Room.Email, "Email")
            <br />
            @Html.EditorFor(m => m.Room.Email)
        </p>
        <p><input type="submit" value="Изменить" /></p>
    </fieldset>
        }
    </div>
</body>
</html>

QuestRoom/Views/Room/Index.cshtml
@using QuestRoom.Models

@model RoomModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div style="text-align:center">
        <img src=/@Model.Room.Pictures.ToList().Find(x => x.Logo == true).Path style="width:450px; height:300px;">
        <p style="font-size:20px; font-style:italic; color:black">Квест - @Model.Room.Name</p>
    </div>
    @RoomHelper.HtmlList(Model.Room.Pictures)
    <hr style="background-color:red; color:red; height:2px; border:none;" />
    <div style="width:40%; margin:10px; display:inline-block; text-align:left">
        <ul style="list-style-type:none">
            <li>@Model.Room.Description</li>
            <li>Время прохождения - @Model.Room.Duration</li>
            <li>Количество человек - @Model.Room.GroupSize</li>
            <li>Ограничение по возрасту - @Model.Room.MinimumAge</li>
            <li>Тип квеста - @Model.TypeRoom.Name</li>
        </ul>
    </div>
    <div style="width:40%; margin:5px; display:inline-block; text-align:right">
        <ul style="list-style-type:none">
            <li>Рейтинг - @Model.Room.Rating</li>
            <li>Уровень сложности - @Model.LevelComplexity.Name</li>
            <li>Адрес - @Model.Room.Address</li>
            <li>Телефон - @Model.Room.PhoneNumbers</li>
            <li>Емейл - @Model.Room.Email</li>
            <li>Компания - @Model.Room.Company</li>
        </ul>
    </div>
</body>
</html>

QuestRoom/Views/Room/LevelComplexity.cshtml
@using QuestRoom.Models
@model CategoryRoomsModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @SortHelper.HtmlList(Model)
</body>
</html>

QuestRoom/Views/Room/TypeRoom.cshtml
@using QuestRoom.Models

@model CategoryRoomsModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @SortHelper.HtmlList(Model)
</body>
</html>

QuestRoom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Редактор", "Index", "Redactor")</li>
                </ul>
            </div>
        </div>
    </div>
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>